# Generated by Django 4.2.16 on 2026-05-29 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('max_tickets', models.IntegerField(default=10, verbose_name='Tickets max simultanés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specializations', models.ManyToManyField(blank=True, to='categories.category', verbose_name='Spécialisations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
            },
        ),
    ]
